services:
  db:
    image: postgres:15
    container_name: MqttIotDBContainer
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - mqttIotPostgres:/var/lib/postgresql/data
    networks:
      - mqttIotNetwork
    restart: unless-stopped
    

  mqtt:
    image: eclipse-mosquitto
    container_name: MqttIotBrokerContainer
    ports:
      - "1883:1883"
    volumes:
      - /home/filip/MqttIotPlatform/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/filip/MqttIotPlatform/mosquitto/data:/mosquitto/data
      - /home/filip/MqttIotPlatform/mosquitto/log:/mosquitto/log
    networks:
      - mqttIotNetwork
    restart: unless-stopped

  mqttDbBridge:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: MqttDbBridgeContainer
    volumes:
      - /home/filip/MqttIotPlatform/mqttDBBridge/program:/app
    networks:
      - mqttIotNetwork
    depends_on:
      - mqtt
      - db
    working_dir: /app
    command: dotnet run
    restart: unless-stopped

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: MqttIotBackendContainer
    volumes:
      - /home/filip/MqttIotPlatform/backend/program:/app
    networks:
      - mqttIotNetwork
    depends_on:
      - mqttDbBridge
      - mqtt
      - db
    ports:
      - "5000:5000"
    working_dir: /app
    command: dotnet run
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: MqttIotFrontendContainer
    ports:
      - "3000:80"
    networks:
      - mqttIotNetwork
    depends_on:
      - backend

networks:
  mqttIotNetwork:
    driver: bridge

volumes:
  mqttIotPostgres: